- name: change email address for admin for RedHat and CentOS
  tags: apache,centos,httpd,redhat
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin shehab_hegazy@yahoo.com
  when: ansible_distribution in ["RedHat", "CentOS"]
  notify: restart_apache # call handler ONLY if result of this play is changed

