- name: Creating a file
  file: 
    path: /tmp/newfile.txt
    state: touch 
    owner: root
    group: root
    mode: '0644'

- name: Creating a directory
  file: 
    path: /tmp/newfile.txt
    state: directory 
    owner: root
    group: root
    mode: '0644'


# to delete any make the state absent instead 