- name: Set password
  user:
    name: shehab
    update_password: always   # always update the password, even if the current password is already set.
    password: "{{ 'abcd123' | password_hash('sha512') }}"