- name: Add SSH Public Key for simone user in authorized_key file
  tags: always,ssh
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPwOZz/n5jW93L8xx9jTAQMtcZgtMOKxjFGVjYW/N8/o Ansible"
    state: present  # Ensures the key is added if it's not already there to avoid duplicates.

- name: Generate sshd_config file from a template
  tags: ssh 
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root 
    mode: '0644'
  notify: restart_sshd